import sys
sys.path.insert(0, '../')

from ll import LinkedList

ll = LinkedList()
ll.append(20)
ll.prepend(19)
ll.append(21)
print("Is 21 present?",ll.find(21))
print("Is 22 present?",ll.find(22))
print(ll)
print("Deleting",ll.delete(20))
print(ll)
print("Deleting 23",ll.delete(23))
ll.insertAtPos(20,1)
print("After insertion of 20 at 1",ll)
print("Cycle length",ll.detectCycleLen())
print("Creating a 3-cycle",ll.createcycle(19))
print("Next of 21:",ll.last.next)
print("Cycle length",ll.detectCycleLen())
print("Chain length",ll.findlen())
ll.createcycle(20)
print("Changing to 2-cycle",ll.last,"<->",ll.last.next)
print("Cycle length",ll.detectCycleLen())
print("Chain length",ll.findlen())
print("LL now:",ll)
ll.delete(19)
print("Deleting head",ll)
ll.delete(21)
print("Deleting last",ll)
print("Head:",ll.head,"Last:",ll.last)
print("Cycle length",ll.detectCycleLen())
ll.delete(20)
print("After deleting 20:",ll)
print("Head:",ll.head,"Last:",ll.last)
print("Chain length",ll.findlen())
ll.append(20)
print("Append 20..")
ll.insertAtPos(21,1)
print("Inserting at pos 1:",ll)
ll.append(22)
print("Appending 22:",ll)
print("Cycle length",ll.detectCycleLen())
print("Chain length",ll.findlen())
print("Fake delete 23:",ll.delete(23))
print("And finally:",ll)



